### ISSUE TITLE
phrase-cli segfauls when the host is incorrect

### ISSUE THREAD

**Issue by strzibny** [phrase/phrase-cli#101]
```bash
$ phrase pull --host localhost:3000/api/v2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8efbfc]

goroutine 1 [running]:
github.com/phrase/phrase-cli/cmd/internal.LocalesForProjects(0xc00023f8c0, 0xb95dc0, 0xc0001f53c8, 0x0, 0x0, 0x0, 0x0, 0x7ffed97cdf39)
	/go/src/github.com/phrase/phrase-cli/cmd/internal/shared.go:38 +0x1bc
github.com/phrase/phrase-cli/cmd/internal.(*PullCommand).Run(0xc000139cb8, 0xc000239450, 0x15, 0x0)
	/go/src/github.com/phrase/phrase-cli/cmd/internal/pull.go:55 +0x21f
github.com/phrase/phrase-cli/cmd.initPull.func1(0xc0002442c0, 0xc000222aa0, 0x0, 0x2)
	/go/src/github.com/phrase/phrase-cli/cmd/pull.go:24 +0xef
github.com/spf13/cobra.(*Command).execute(0xc0002442c0, 0xc000222a80, 0x2, 0x2, 0xc0002442c0, 0xc000222a80)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xe51a00, 0x41aa01, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/phrase/phrase-cli/cmd.Execute()
	/go/src/github.com/phrase/phrase-cli/cmd/root.go:64 +0x2d
main.main()
	/go/src/github.com/phrase/phrase-cli/main.go:8 +0x25
```
We should probably show a friendly error message and document the `/api/v2` path in `--help`.

**Comment by forelabs** [comment]
Resolved. We now show

> Error: Get "localhost:3000/api/v2/projects/1d8ae641902624df63ce6fbd64ff9549/locales?page=1&per_page=100": unsupported protocol scheme "localhost"
